// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0H4ZEFqZtYyQr2VmVF0iFscwsXWo0X64',
    appId: '1:881630426053:web:99db13879280cfcdf3d1ac',
    messagingSenderId: '881630426053',
    projectId: 'hotncold-9f6ab',
    authDomain: 'hotncold-9f6ab.firebaseapp.com',
    storageBucket: 'hotncold-9f6ab.appspot.com',
    measurementId: 'G-2BQE6V0KPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQZF9sqKSrddeNTOz888_o59hwiuvLfI',
    appId: '1:881630426053:android:9d66397764c02d64f3d1ac',
    messagingSenderId: '881630426053',
    projectId: 'hotncold-9f6ab',
    storageBucket: 'hotncold-9f6ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxWBBCC1b_hALgFMImdHgBZuQ71QZ92k',
    appId: '1:881630426053:ios:80fec2ae18d5c278f3d1ac',
    messagingSenderId: '881630426053',
    projectId: 'hotncold-9f6ab',
    storageBucket: 'hotncold-9f6ab.appspot.com',
    iosClientId: '881630426053-b8g2gk9a7omktkisjd1tanb3frn76bbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotncold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxWBBCC1b_hALgFMImdHgBZuQ71QZ92k',
    appId: '1:881630426053:ios:80fec2ae18d5c278f3d1ac',
    messagingSenderId: '881630426053',
    projectId: 'hotncold-9f6ab',
    storageBucket: 'hotncold-9f6ab.appspot.com',
    iosClientId: '881630426053-b8g2gk9a7omktkisjd1tanb3frn76bbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotncold',
  );
}
